const express = require("express");
const router = express.Router();

const search = require("../controller/ticket/search");
const ticketDescription = require("../controller/ticket/ticketDescription");
const ticketPriceInfo = require("../controller/ticket/ticketPriceInfo");
const ticketPerformanceDate = require("../controller/ticket/ticketPerformanceDate");
const ticketPerformanceTime = require("../controller/ticket/ticketPerformanceTime");
const ticketSeatClass = require("../controller/ticket/ticketSeatClass");
const ticketSeatNo = require("../controller/ticket/ticketSeatNo");
const ticketPrice = require("../controller/ticket/ticketPrice");
const ticketTokenIdAndOwner = require("../controller/ticket/ticketTokenIdAndOwner");
const updateTicketOwner = require("../controller/ticket/updateTicketOwner");
const comingSoon = require("../controller/ticket/comingSoon");
const ticketInfo = require("../controller/ticket/ticketInfo");
const ticketSeatImageUrl = require("../controller/ticket/ticketSeatImageUrl");
const hotPick = require("../controller/ticket/hotPick");
const deadLineTop5 = require("../controller/ticket/deadLineTop5");
const deadLineAll = require("../controller/ticket/deadLineAll");
const ticketInfoByTokenId = require("../controller/ticket/ticketInfoByTokenId");

router.get('/search/:keyword', search);
router.get('/ticketDescription/:product_name', ticketDescription);
router.get('/ticketPriceInfo/:product_name', ticketPriceInfo);
router.post('/ticketPerformanceDate', ticketPerformanceDate);
router.post('/ticketPerformanceTime', ticketPerformanceTime);
router.post('/ticketSeatClass', ticketSeatClass);
router.post('/ticketSeatNo', ticketSeatNo);
router.post('/ticketPrice', ticketPrice);
router.post('/ticketTokenIdAndOwner', ticketTokenIdAndOwner);
router.post('/updateTicketOwner', updateTicketOwner);
router.get('/comingSoon', comingSoon);
router.get('/ticketInfo', ticketInfo);
router.get('/ticketSeatImageUrl', ticketSeatImageUrl);
router.get('/hotPick', hotPick);
router.get('/deadLineTop5', deadLineTop5);
router.get('/deadLineAll', deadLineAll);
router.get('/ticketInfoByTokenId/:token_id', ticketInfoByTokenId);

module.exports = router;